export const serverRespondList = {
  numFound: 34,
  docs: [
    {
      author_name: ["George Orwell"],
      title: "1984",
      edition_count: 12,
      first_publish_year: 1949,
    },
    {
      author_name: ["J.K. Rowling"],
      title: "Harry Potter and the Philosopher's Stone",
      edition_count: 7,
      first_publish_year: 1997,
    },
    {
      author_name: ["F. Scott Fitzgerald"],
      title: "The Great Gatsby",
      edition_count: 5,
      first_publish_year: 1925,
    },
    {
      author_name: undefined, // Если автор неизвестен
      title: "Mysterious Tales",
      edition_count: 3,
      first_publish_year: undefined,
    },
    {
      author_name: ["J.R.R. Tolkien"],
      title: "The Hobbit",
      edition_count: 8,
      first_publish_year: 1937,
    },
    {
      author_name: ["Harper Lee"],
      title: "To Kill a Mockingbird",
      edition_count: 10,
      first_publish_year: 1960,
    },
    {
      author_name: ["Isaac Asimov"],
      title: "Foundation",
      edition_count: 6,
      first_publish_year: 1951,
    },
    {
      author_name: undefined,
      title: "Ancient Mysteries",
      edition_count: 2,
      first_publish_year: undefined,
    },
    {
      author_name: ["Leo Tolstoy"],
      title: "War and Peace",
      edition_count: 11,
      first_publish_year: 1869,
    },
    {
      author_name: ["Mark Twain"],
      title: "Adventures of Huckleberry Finn",
      edition_count: 4,
      first_publish_year: 1884,
    },
    {
      author_name: undefined,
      title: "Unknown Book",
      edition_count: 1,
      first_publish_year: undefined,
    },
    {
      author_name: ["Arthur Conan Doyle"],
      title: "Sherlock Holmes: A Study in Scarlet",
      edition_count: 5,
      first_publish_year: 1887,
    },
    {
      author_name: ["H.G. Wells"],
      title: "The War of the Worlds",
      edition_count: 3,
      first_publish_year: 1898,
    },
    {
      author_name: ["Jane Austen"],
      title: "Pride and Prejudice",
      edition_count: 9,
      first_publish_year: 1813,
    },
    {
      author_name: ["Ernest Hemingway"],
      title: "The Old Man and the Sea",
      edition_count: 6,
      first_publish_year: 1952,
    },
    {
      author_name: ["Charles Dickens"],
      title: "Great Expectations",
      edition_count: 8,
      first_publish_year: 1861,
    },
    {
      author_name: ["Ray Bradbury"],
      title: "Fahrenheit 451",
      edition_count: 7,
      first_publish_year: 1953,
    },
    {
      author_name: ["Gabriel Garcia Marquez"],
      title: "One Hundred Years of Solitude",
      edition_count: 5,
      first_publish_year: 1967,
    },
    {
      author_name: ["Franz Kafka"],
      title: "The Metamorphosis",
      edition_count: 4,
      first_publish_year: 1915,
    },
    {
      author_name: ["J.D. Salinger"],
      title: "The Catcher in the Rye",
      edition_count: 5,
      first_publish_year: 1951,
    },
    {
      author_name: ["Aldous Huxley"],
      title: "Brave New World",
      edition_count: 6,
      first_publish_year: 1932,
    },
    {
      author_name: ["Dante Alighieri"],
      title: "The Divine Comedy",
      edition_count: 3,
      first_publish_year: 1320,
    },
    {
      author_name: ["Homer"],
      title: "The Odyssey",
      edition_count: 7,
      first_publish_year: undefined,
    },
    {
      author_name: undefined,
      title: "Lost Legends",
      edition_count: 2,
      first_publish_year: undefined,
    },
    {
      author_name: ["Miguel de Cervantes"],
      title: "Don Quixote",
      edition_count: 9,
      first_publish_year: 1605,
    },
    {
      author_name: ["Fyodor Dostoevsky"],
      title: "Crime and Punishment",
      edition_count: 5,
      first_publish_year: 1866,
    },
    {
      author_name: ["Mary Shelley"],
      title: "Frankenstein",
      edition_count: 4,
      first_publish_year: 1818,
    },
    {
      author_name: undefined,
      title: "Forgotten Histories",
      edition_count: 1,
      first_publish_year: undefined,
    },
    {
      author_name: ["Virginia Woolf"],
      title: "Mrs. Dalloway",
      edition_count: 3,
      first_publish_year: 1925,
    },
    {
      author_name: ["William Shakespeare"],
      title: "Hamlet",
      edition_count: 8,
      first_publish_year: 1600,
    },
    {
      author_name: ["Herman Melville"],
      title: "Moby-Dick",
      edition_count: 6,
      first_publish_year: 1851,
    },
    {
      author_name: undefined,
      title: "Unknown Seas",
      edition_count: 2,
      first_publish_year: undefined,
    },
    {
      author_name: ["Emily Brontë"],
      title: "Wuthering Heights",
      edition_count: 5,
      first_publish_year: 1847,
    },
    {
      author_name: ["Jules Verne"],
      title: "Twenty Thousand Leagues Under the Sea",
      edition_count: 7,
      first_publish_year: 1870,
    },
  ],
};

export const filteredBooksList = [
  {
    author: "George Orwell",
    title: "1984",
    editionCount: 12,
    firstPublishYear: 1949,
  },
  {
    author: "J.K. Rowling",
    title: "Harry Potter and the Philosopher's Stone",
    editionCount: 7,
    firstPublishYear: 1997,
  },
  {
    author: "F. Scott Fitzgerald",
    title: "The Great Gatsby",
    editionCount: 5,
    firstPublishYear: 1925,
  },
  {
    author: "Unknown author",
    title: "Mysterious Tales",
    editionCount: 3,
    firstPublishYear: "N/A",
  },
  {
    author: "J.R.R. Tolkien",
    title: "The Hobbit",
    editionCount: 8,
    firstPublishYear: 1937,
  },
  {
    author: "Harper Lee",
    title: "To Kill a Mockingbird",
    editionCount: 10,
    firstPublishYear: 1960,
  },
  {
    author: "Isaac Asimov",
    title: "Foundation",
    editionCount: 6,
    firstPublishYear: 1951,
  },
  {
    author: "Unknown author",
    title: "Ancient Mysteries",
    editionCount: 2,
    firstPublishYear: "N/A",
  },
  {
    author: "Leo Tolstoy",
    title: "War and Peace",
    editionCount: 11,
    firstPublishYear: 1869,
  },
  {
    author: "Mark Twain",
    title: "Adventures of Huckleberry Finn",
    editionCount: 4,
    firstPublishYear: 1884,
  },
  {
    author: "Unknown author",
    title: "Unknown Book",
    editionCount: 1,
    firstPublishYear: "N/A",
  },
  {
    author: "Arthur Conan Doyle",
    title: "Sherlock Holmes: A Study in Scarlet",
    editionCount: 5,
    firstPublishYear: 1887,
  },
  {
    author: "H.G. Wells",
    title: "The War of the Worlds",
    editionCount: 3,
    firstPublishYear: 1898,
  },
  {
    author: "Jane Austen",
    title: "Pride and Prejudice",
    editionCount: 9,
    firstPublishYear: 1813,
  },
  {
    author: "Ernest Hemingway",
    title: "The Old Man and the Sea",
    editionCount: 6,
    firstPublishYear: 1952,
  },
  {
    author: "Charles Dickens",
    title: "Great Expectations",
    editionCount: 8,
    firstPublishYear: 1861,
  },
  {
    author: "Ray Bradbury",
    title: "Fahrenheit 451",
    editionCount: 7,
    firstPublishYear: 1953,
  },
  {
    author: "Gabriel Garcia Marquez",
    title: "One Hundred Years of Solitude",
    editionCount: 5,
    firstPublishYear: 1967,
  },
  {
    author: "Franz Kafka",
    title: "The Metamorphosis",
    editionCount: 4,
    firstPublishYear: 1915,
  },
  {
    author: "J.D. Salinger",
    title: "The Catcher in the Rye",
    editionCount: 5,
    firstPublishYear: 1951,
  },
  {
    author: "Aldous Huxley",
    title: "Brave New World",
    editionCount: 6,
    firstPublishYear: 1932,
  },
  {
    author: "Dante Alighieri",
    title: "The Divine Comedy",
    editionCount: 3,
    firstPublishYear: 1320,
  },
  {
    author: "Homer",
    title: "The Odyssey",
    editionCount: 7,
    firstPublishYear: "N/A",
  },
  {
    author: "Unknown author",
    title: "Lost Legends",
    editionCount: 2,
    firstPublishYear: "N/A",
  },
  {
    author: "Miguel de Cervantes",
    title: "Don Quixote",
    editionCount: 9,
    firstPublishYear: 1605,
  },
  {
    author: "Fyodor Dostoevsky",
    title: "Crime and Punishment",
    editionCount: 5,
    firstPublishYear: 1866,
  },
  {
    author: "Mary Shelley",
    title: "Frankenstein",
    editionCount: 4,
    firstPublishYear: 1818,
  },
  {
    author: "Unknown author",
    title: "Forgotten Histories",
    editionCount: 1,
    firstPublishYear: "N/A",
  },
  {
    author: "Virginia Woolf",
    title: "Mrs. Dalloway",
    editionCount: 3,
    firstPublishYear: 1925,
  },
  {
    author: "William Shakespeare",
    title: "Hamlet",
    editionCount: 8,
    firstPublishYear: 1600,
  },
  {
    author: "Herman Melville",
    title: "Moby-Dick",
    editionCount: 6,
    firstPublishYear: 1851,
  },
  {
    author: "Unknown author",
    title: "Unknown Seas",
    editionCount: 2,
    firstPublishYear: "N/A",
  },
  {
    author: "Emily Brontë",
    title: "Wuthering Heights",
    editionCount: 5,
    firstPublishYear: 1847,
  },
  {
    author: "Jules Verne",
    title: "Twenty Thousand Leagues Under the Sea",
    editionCount: 7,
    firstPublishYear: 1870,
  },
];
